version: '3.8'

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      
    working_dir: /usr/src/app
    #volumes:
   #   - .:/usr/src/app
    #  - ./mochawesome-report:/usr/src/app/mochawesome-report
    command: npm run testReport