name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and run tests
        uses: docker/compose-action@v3
        with:
          compose-file: ./docker-compose.yml
          up-flags: --build --exit-code-from test-runner

      - name: Generate Mochawesome report
        run: docker-compose run test-runner npm run report

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
          retention-days: 7
      - name: Shutdown Docker Compose
        run: docker-compose down --volumes
